config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root to: "home#index"

  get "/order/details/" , to: "order#order_details"
  
  resources :home do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  post '/comments/:id', to: 'comments#create_reply'

  #resources :home, only: [:index, :show]
  resources :order, only: [:index, :show, :create]

  resources :basket do
    collection do
      post '/:id', to: 'basket#create', as: 'basket'
      delete '/:id', to: 'basket#destroy', as: 'basket_delete'
    end
  end

  resources :profile, only: [:index, :show, :update]
  put "/profile", to: "profile#update"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/basket.rb
class Basket < ApplicationRecord
    belongs_to :user
    belongs_to :product

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    belongs_to :user
    has_many :reply

    def self.ransackable_attributes(auth_object = nil)
        ["body", "created_at", "id", "product_id", "updated_at", "user_id"]
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_status", "product_id", "updated_at", "user_id"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
    include PgSearch::Model

    pg_search_scope :search_by_title, against: { title: 'A' , description: 'B'}, using: { tsearch: { dictionary: 'english', tsvector_column: 'searchable', prefix: true} }
    pg_search_scope :search_by_brand, against: :brand, using: { tsearch: { dictionary: 'english' } }

    has_many :comment

    def self.ransackable_attributes(auth_object = nil)
        ["brand", "category", "created_at", "description", "discountPercentage", "id", "images", "price", "rating", "searchable", "stock", "thumnail", "title", "updated_at"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["comment"]
    end
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :user
    belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  scope :lower_username, -> (username) { where("lower(username) like ?", "%#{username}%")  }

  has_many :basket
  has_many :order
  has_many :comment
  has_many :reply
  has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :avatar, :adress, :phone, :country)}
        end
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
    def index
        @basket = current_user.basket.all
        @total_price = 0
        @basket.each do |item|  @total_price += item.product.price end
    end

    def create
        @basket = current_user.basket.create(user_id:current_user.id, product_id:params[:id])
        redirect_to "/", notice: 'Product successfully added to your basket!'
    end 

    def destroy
        @basket = current_user.basket.find(params[:id]).destroy
        redirect_to "/basket", notice: 'Product successfully deleted from your basket!'
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @comment = Comment.new
    end

    def create
        @p = Product.find(params[:comment][:product])
        @comment = Comment.new(body: params[:comment][:body], product: @p, user: current_user )
        if @comment.save
            redirect_to "/", notice: 'Your comment was successfully posted!'
        else
            redirect_to "/", notice: "Your comment wasn't posted!"
        end
    end

    def create_reply
        @com = Comment.find(params[:id])
        @reply = Reply.new(reply_body: params[:reply][:reply_body], comment: @com, user:current_user)
        if @reply.save
            redirect_to "/", notice: 'Your reply was successfully posted!'
        else
            redirect_to "/", notice: "Your reply wasn't posted!"
        end
        
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, :only => [:show]
    def index
        if params[:title] || params[:brand]
            
            parameter = filter_params

            if parameter["title"]
                
                @pagy, @products = pagy(Product.search_by_title(parameter["title"]))
            else
                @pagy, @products = pagy( Product.search_by_brand(parameter["brand"])) 
            end

        else
            @pagy, @products = pagy(Product.all)
        end
    end

    def show
        @com = Comment.find(2)
        puts @com.reply
        puts "^^^^^^^^^^^^^^^^^"
        @item = Product.find(params[:id])
    end


    private 

    def filter_params
        params.delete_if{|key,value| value.blank? || value=="home" || value=="index" || value=="---" || value=="Search"}
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    def index
        @basket = current_user.basket.all
        @total_price = 0
        @basket.each do |item|  @total_price += item.product.price end
    end

    def show
        @item = Product.find(params[:id])
    end

    def create
        '''
        Order status can be:
            - Pending
            - Packaged
            - Shipped
            - Cancelled
        '''

        if params[:product_id]
            @order = current_user.order.create(user_id:current_user.id, product_id:params[:product_id], order_status:"Pending")
            redirect_to "/", notice: 'Product successfully ordered!' and return
        end

        current_user.basket.all.each do |item|
            current_user.order.create(order_status:"Pending", user_id: current_user.id, product_id: item.product_id)
        end
        current_user.basket.all.destroy_all
        redirect_to "/", notice: 'Products successfully ordered!'
    end

    def order_details
        @pagy, @user_orders = pagy(current_user.order.all)
        render "details"
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end

  def show
  end

  def update
    if current_user.update(profile_update_params.delete_if{ |key,value| value.blank? })
      redirect_to "/profile" , notice: 'Profile updated'
    else
      redirect_to "/"
    end

  end

  private
  def profile_update_params
    temp_hash = {}
    temp_hash["country"] = params[:country]
    temp_hash["phone"] = params[:phone]
    temp_hash["adress"] = params[:adress]
    temp_hash["username"] = params[:username]
    temp_hash
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend

end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/basket/index.html.haml
%body{:style => "background-color: #eee;"}
  - if current_user.basket.all.count < 1
    %section.h-100.gradient-custom
      .container.py-5.h-100
        .row.d-flex.justify-content-center.align-items-center.h-100
          .col-lg-10.col-xl-8
            .card{style: "border-radius: 10px;"}
              .card-header.px-4.py-5
                %h5.text-muted.mb-0
                  Sorry your basket is empty,
                  %span{style: "color: #a8729a;"} #{current_user.username}
                  = link_to "Go Home", root_path, class: 'btn btn-primary'
  - else
    %section.h-100.gradient-custom
      .container.py-5.h-100
        .row.d-flex.justify-content-center.align-items-center.h-100
          .col-lg-10.col-xl-8
            .card{style: "border-radius: 10px;"}
              .card-header.px-4.py-5
                %h5.text-muted.mb-0
                  Here is your basket,
                  %span{style: "color: #a8729a;"} #{current_user.username}

              .card-body.p-4
                .d-flex.justify-content-between.align-items-center.mb-4
                  %p.lead.fw-normal.mb-0{style: "color: #a8729a;"} Receipt
                  %p.small.text-muted.mb-0 Receipt Voucher : 1KAU9-84UIL
                - @basket.each do | item |
                  .card.shadow-0.border.mb-4
                    .card-body
                      .row
                        .col-md-2
                          %img.img-fluid{alt: "Phone", src: "#{item.product.images[0]}"}/
                        .col-md-2.text-center.d-flex.justify-content-center.align-items-center
                          %p.text-muted.mb-0 #{ item.product.title }
                        .col-md-2.text-center.d-flex.justify-content-center.align-items-center
                          %p.text-muted.mb-0.small Rating: #{ item.product.rating }
                        .col-md-2.text-center.d-flex.justify-content-center.align-items-center
                          %p.text-muted.mb-0.small Disc. % #{ item.product.discountPercentage }
                        .col-md-2.text-center.d-flex.justify-content-center.align-items-center
                          %p.text-muted.mb-0.small Qty: 1
                        .col-md-2.text-center.d-flex.justify-content-center.align-items-center
                          %p.text-muted.mb-0.small#price $ #{ item.product.price }
                        .col-md-2.text-center.d-flex.justify-content-center.align-items-center
                          = button_to "Delete",  {:controller => :basket, :action => 'destroy', :id => item.id}, :method => :delete, :class => 'btn btn-danger'
                  %hr.mb-4{style: "background-color: #e0e0e0; opacity: 1;"}/


                .d-flex.justify-content-between.pt-2

                  %p.fw-bold.mb-0 Order Details
                  %p.text-muted.mb-0
                    %span.fw-bold.me-4 Total
                    $898.00
                .d-flex.justify-content-between.pt-2
                  %p.text-muted.mb-0 Invoice Number : 788152
                  %p.text-muted.mb-0
                    %span.fw-bold.me-4 Discount
                    $19.00
                .d-flex.justify-content-between
                  %p.text-muted.mb-0 Invoice Date : #{ Time.now.strftime('%Y-%m-%d')}
                  %p.text-muted.mb-0
                    %span.fw-bold.me-4 GST 18%
                    123
                .d-flex.justify-content-between.mb-5
                  %p.text-muted.mb-0 Recepits Voucher : 18KU-62IIK
                  %p.text-muted.mb-0
                    %span.fw-bold.me-4 Delivery Charges
                    Free
              .card-footer.border-0.px-4.py-5{style: "background-color: #a8729a; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;"}
                - if !current_user.basket.all.empty?
                  = link_to "Place Order", order_index_url, class: 'btn btn-info'
                = link_to "Go Home", root_path, class: 'btn btn-primary'
                %h5.d-flex.align-items-center.justify-content-end.text-white.text-uppercase.mb-0
                  Total
                  paid:
                  %span.h2.mb-0.ms-2#price-total  $#{ @total_price }
                  

app/views/comments/_comment.html.haml
%li
  = comment.body
  \-
  %small
    Submitted #{time_ago_in_words(comment.created_at)} ago
    \- By #{comment.user.username}
  
  - if comment.reply.all.count >= 1
    %br
    %br
    %bold 
      Replies
      - comment.reply.all.each do |replies|
        %li
          #{ replies.reply_body }
  
  = form_for [comment, Reply.new], url: comment_path do |f|
    = f.text_area :reply_body, placeholder: "Add a Reply"
    %br/
    
    = f.submit "Reply"
      
  %hr  

app/views/home/edit.html.haml
%body{:style => "background-color: #eee;"}
  %section.p-4.p-md-5
    .row.d-flex.justify-content-center
     
      .col-md-10.col-lg-8.col-xl-5
        %h4
          Hey,
          #{ current_user.username }
          %small please fill the form
        .card.rounded-3
          .card-body.p-4
            .text-center.mb-4
              %h3 #{ @item.title }
              %h6 
                Total Price:
                #{ @item.price }
                $
            %form{action: ""}
              %p.fw-bold.mb-4.pb-2 Enter your credentials:
              .form-outline.mb-4
                %input#formControlLgXsd.form-control.form-control-lg{type: "text", value: "Anna Doe"}/
                %label.form-label{for: "formControlLgXsd"} Cardholder's Name
              .row.mb-4
                .col-7
                  .form-outline
                    %label Card Number
                    %input#formControlLgXM.form-control.form-control-lg{type: "text", value: "1234 5678 1234 5678"}/
                    %img.img-fluid{src: "https://img.icons8.com/color/48/000000/visa.png"}
                .col-3
                  .form-outline
                    %label.form-label{for: "formControlLgExpk"} Expire
                    %input#formControlLgExpk.form-control.form-control-lg.mb-2{placeholder: "MM/YYYY", type: "password"}/
                   
                .col-2
                  .form-outline
                    %label.form-label{for: "formControlLgcvv"} Cvv
                    %input#formControlLgcvv.form-control.form-control-lg{placeholder: "Cvv", type: "password"}/
              %button.btn.btn-success.btn-lg.btn-block Pay 

app/views/home/index.html.haml
%body{:style => "background-color: #eee;"}
- if current_user.present?
  %section.p-4.p-md-5
    .col-lg-12
      .container{:style=> "max-width:1530px;"}
        .col-sm
          %h4
            Welcome,
            %strong #{ current_user.username }
        .col-sm
          %h4
            Today is
            %strong #{Time.now.strftime("%A")}
        .col-sm
          = link_to basket_index_url do
            %i.bi.bi-basket3{class: 'btn btn-primary'}
            &nbsp
          = link_to profile_index_url do
            %i.bi.bi-person-circle{class: 'btn btn-info'}

%br
.col-lg-12
  .container{:style=> "max-width:1530px;"}
    = form_with model: @product, class: 'row', url: "/home", method: "get" do |form|
      .col-sm-3
        = form.label "Text Search"
        = form.text_field :title , class: "form-control", placeholder: "Iphone, laptop, perfume etc."
      .col-sm-3 
        = form.label "Select Brand"
        = form.select :brand, ['---', 'Apple', 'Samsung', 'Huawei', 'Oppo'], {}, { :class =>'form-select' }
      .col-auto.mt-4
        = form.button class: 'btn btn-info' do
          %i.bi.bi-search
            Search

    .col-auto.mt-4
      - if current_user.present?
        = button_to destroy_user_session_path, method: :delete, class: 'btn btn-danger' do
          %i.bi.bi-box-arrow-in-left
            Sign out
      -else
        = button_to new_user_session_path, method: :get, class: 'btn btn-success' do
          %i.bi.bi-box-arrow-in-right
            Log in 

%br
.container.col-lg-12{:style=> "max-width:1520px;"}
  .row
    - @products.each do |item|
      .card{style: "width: 18rem;"}
        %a{href: url_for(item.images[0])}
          %img.card-img-top{alt: "...", src: item.images[0],}
        .card-body
          %h5.card-title #{item.title}
          %p.card-text #{item.description}
          = link_to "#{item.price}$", home_path(:id => item.id), class: 'btn btn-primary'
          = button_to  basket_url(:id => item.id), class: 'btn btn-info' do
            %i.bi.bi-bag-plus-fill
              Add to basket

    != pagy_bootstrap_nav(@pagy)

    

app/views/home/show.html.haml
%body{:style => "background-color: #eee;"}
  %section.vh-100.gradient-custom-2
    .container.py-5.h-100
      
      .row.d-flex.justify-content-center.align-items-center.h-100
        .col-md-10.col-lg-8.col-xl-8
          .h4 Detail Page
          .card.card-stepper{style: "border-radius: 16px;"}
            .card-header.p-4
              .d-flex.justify-content-between.align-items-center
                %div
                  %p.text-muted.mb-2
                    Stock Count:
                    %span.fw-bold.text-body #{ @item.stock }
                  %p.text-muted.mb-0
                    Place On:
                    %span.fw-bold.text-body #{ @item.created_at }
                  %p.text-muted.mt-1
                    Category:
                    %span.fw-bold.text-body #{ @item.category }
                %div
                  %h6.mb-0
                    = link_to "Place Order", order_path(:id => @item.id), class: 'btn btn-primary'
            .card-body.p-4
              .d-flex.flex-row.mb-4.pb-2
                .flex-fill
                  %h5.bold #{ @item.title }
                  %p.text-muted #{ @item.description }
                  %h4.mb-3
                    #{@item.price}$
                    %span.small.text-muted via (COD)
                  %p.text-muted
                    Visited on:
                    %span.text-body #{Time.now.strftime("%H %M")}, #{Time.now.strftime("%A")} 
                  %p.text-muted
                    Rating:
                    %span.text-body #{ @item.rating }

                  = link_to "Go Home", root_path, class: 'btn btn-primary'
                %div
                  %img.align-self-center.img-fluid{src: @item.images[0]}
              
              .container
                %h3.bold Comments
                = form_for(Comment.new) do |f|
                  = f.text_area :body, placeholder: "Add Comment"
                  = f.hidden_field :user, value: current_user.id
                  = f.hidden_field :product, value: @item.id
                  = f.submit

                %ul
                  =render(partial: 'comments/comment', collection: @item.comment)
                 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Commerce Web
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    - if notice
      %p.alert.alert-primary= notice
    
    - if alert
      %p.alert.alert-danger= alert
    
    = yield      

app/views/order/details.html.haml
%style
  :plain
    @import url('https://fonts.googleapis.com/css?family=Assistant');
    body {
      background: #eee;
      font-family: Assistant, sans-serif;
    }

    .cell-1 {
      border-collapse: separate;
      border-spacing: 0 4em;
      background: #fff;
      border-bottom: 5px solid transparent;
      /*background-color: gold;*/
      background-clip: padding-box;
    }

    thead {
      background: #dddcdc;
    }

    .toggle-btn {
      width: 40px;
      height: 21px;
      background: grey;
      border-radius: 50px;
      padding: 3px;
      cursor: pointer;
      -webkit-transition: all 0.3s 0.1s ease-in-out;
      -moz-transition: all 0.3s 0.1s ease-in-out;
      -o-transition: all 0.3s 0.1s ease-in-out;
      transition: all 0.3s 0.1s ease-in-out;
    }

    .toggle-btn > .inner-circle {
      width: 15px;
      height: 15px;
      background: #fff;
      border-radius: 50%;
      -webkit-transition: all 0.3s 0.1s ease-in-out;
      -moz-transition: all 0.3s 0.1s ease-in-out;
      -o-transition: all 0.3s 0.1s ease-in-out;
      transition: all 0.3s 0.1s ease-in-out;
    }

    .toggle-btn.active {
      background: blue !important;
    }

    .toggle-btn.active > .inner-circle {
      margin-left: 19px;
    }
.container.mt-5
  .d-flex.justify-content-center.row
    .col-md-10
      %h5
        Order history table for
        %strong #{ current_user.username }
      .rounded
        .table-responsive.table-borderless
          %table.table
            %thead
              %tr
                %th Order #
                %th Company Name
                %th Product Name
                %th Status
                %th Total
                %th Created At
                %th
            %tbody.table-body
              - @user_orders.each do |item|
                %tr.cell-1
                  %td #{ item.id }
                  %td #{ item.product.brand }
                  %td #{ item.product.title }
                  %td #{ item.order_status }
                  %td $ #{ item.product.price }
                  %td #{ item.created_at.strftime('%a, %d %b %Y %H:%M:%S') }
                  %td
                    %i.fa.fa-ellipsis-h.text-black-50
        != pagy_bootstrap_nav(@pagy)
        = link_to "Go Back", profile_index_url, class: 'btn btn-primary'

app/views/order/index.html.haml
%body{:style => "background-color: #eee;"}
  %section.p-4.p-md-5
    .row.d-flex.justify-content-center
     
      .col-md-10.col-lg-8.col-xl-5
        %h4
          Hey,
          #{ current_user.username }
          %small please fill the form to pay.
        .card.rounded-3
          .card-body.p-4
          
            .text-center.mb-4
              - @basket.each do |item|
                %h3 #{ item.product.title }
                %h6 
                  Price:
                  #{ item.product.price }
                  $
            %p.fw-bold.mb-2.pb-3 Your total payment: #{ @total_price } $
            %hr
            %p.fw-bold.mb-4.pb-2 Enter your credentials:
            .form-outline.mb-4
              %input#formControlLgXsd.form-control.form-control-lg{type: "text", value: "Anna Doe"}/
              %label.form-label{for: "formControlLgXsd"} Cardholder's Name
            .row.mb-4
              .col-7
                .form-outline
                  %label Card Number
                  %input#formControlLgXM.form-control.form-control-lg{type: "text", value: "1234 5678 1234 5678"}/
                  %img.img-fluid{src: "https://img.icons8.com/color/48/000000/visa.png"}
              .col-6
                .form-outline
                  %label.form-label{for: "formControlLgExpk"} Expire Date
                  %input#formControlLgExpk.form-control.form-control-lg.mb-2{placeholder: "MM/YYYY", type: "password"}/
                  
              .col-2
                .form-outline
                  %label.form-label{for: "formControlLgcvv"} Cvv
                  %input#formControlLgcvv.form-control.form-control-lg{placeholder: "Cvv", type: "password"}/
            = button_to "Pay",  {:controller => :order, :action => 'create'}, :method => :post, :class => 'btn btn-success'
            = link_to "Go Home", root_path, class: 'btn btn-primary'

app/views/order/show.html.haml
%body{:style => "background-color: #eee;"}
  %section.p-4.p-md-5
    .row.d-flex.justify-content-center
     
      .col-md-10.col-lg-8.col-xl-5
        %h4
          Hey,
          #{ current_user.username }
          %small please fill the form
        .card.rounded-3
          .card-body.p-4
            .text-center.mb-4
              %h3 #{ @item.title }
              %h6 
                Total Price:
                #{ @item.price }
                $
            
            %p.fw-bold.mb-4.pb-2 Enter your credentials:
            .form-outline.mb-4
              %input#formControlLgXsd.form-control.form-control-lg{type: "text", value: "Anna Doe"}/
              %label.form-label{for: "formControlLgXsd"} Cardholder's Name
            .row.mb-4
              .col-7
                .form-outline
                  %label Card Number
                  %input#formControlLgXM.form-control.form-control-lg{type: "text", value: "1234 5678 1234 5678"}/
                  %img.img-fluid{src: "https://img.icons8.com/color/48/000000/visa.png"}
              
              .col-6
                .form-outline
                  %label.form-label{for: "formControlLgExpk"} Expire
                  %input#formControlLgExpk.form-control.form-control-lg.mb-2{placeholder: "MM/YYYY", type: "password"}/
              
              .col-6
                .form-outline
                  %label.form-label{for: "formControlLgcvv"} Cvv
                  %input#formControlLgcvv.form-control.form-control-lg{placeholder: "Cvv", type: "password"}/
            = button_to "Pay",  {:controller => :order, :action => 'create', :product_id => @item.id}, :method => :post, :class => 'btn btn-success'
            = link_to "Go Home", root_path, class: 'btn btn-primary'

  :javascript
    function success() {
      alert("Your payment is succsess!")
    }